--- 
- hosts: staging
  tasks:
    - name: "Copy keys to servers"
      copy: 
          group: sudo
          src: "{{ item.0 }}"
          dest: "{{ item.1 }}"
          mode: 0600
          owner: shashwat
      with_together:
        - ['/home/shashwat/.ssh/id_rsa']
        - ['~/.ssh/']


