--- 
- hosts: web
  tasks:
    - name: "Copy keys to servers"
      copy: 
          group: sudo
          src: "{{ item.0 }}"
          dest: "{{ item.1 }}"
          mode: 600
          owner: shashwat
          # src: /home/shashwat/.ssh/id_rsa
          # dest: ~/.ssh/
      with_together:
        - ['/home/shashwat/.ssh/id_rsa', '/home/shashwat/.ssh/id_rsa.pub']
        - ['~/.ssh/', '~/.ssh/']


